/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acchiappalatalpa;

/**
 *
 * @author onorati.nicolo
 */
import java.awt.Color;
import javax.swing.*;

import java.awt.Color;
import java.util.ArrayList;


public class Interfaccia extends javax.swing.JFrame {
    private ArrayList<RoundButton> listaBuche = new ArrayList<>();
    private Gestore gestore;
    private Giocatore giocatore;
    
    private final Color coloreTalpa = new Color(139, 69, 19); // Questo crea il Marrone

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());

    /**
     * Creates new form Interfaccia
     */
    
   public Interfaccia() {
        initComponents(); // Inizializza lbl_punteggio e lblTimer dalla palette
    
    // Inizializziamo il giocatore UNA sola volta
    giocatore = new Giocatore(lbl_punteggio);

    // Setup finestra
    setTitle("Acchiappa la Talpa");
    setSize(450, 600); 
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setLocationRelativeTo(null);
    getContentPane().setLayout(null);

    int buttonSize = 100;
    int gap = 20;
    int startX = 50;
    int startY = 100; 

    // Ciclo per creare le buche
    for (int row = 0; row < 3; row++) {
        for (int col = 0; col < 3; col++) {
            RoundButton hole = new RoundButton("");
            hole.setBackground(Color.lightGray);
            
            int x = startX + col * (buttonSize + gap);
            int y = startY + row * (buttonSize + gap);
            hole.setBounds(x, y, buttonSize, buttonSize);

            // UN SOLO ActionListener che gestisce tutto
            hole.addActionListener(e -> {
                if (hole.getBackground().equals(coloreTalpa)) {
                    giocatore.incrementaPunteggio();
                    hole.setBackground(Color.lightGray); // La talpa sparisce se colpita
                } else {
                    giocatore.decrementaPunteggio(); // Errore: clic sulla buca vuota
                }
            });
            
            listaBuche.add(hole);
            getContentPane().add(hole);
        }
    }
    
    // AVVIO DEL GIOCO: Usiamo 'lblTimer' perché è così che si chiama nel tuo initComponents
    gestore = new Gestore(listaBuche, lblTimer, giocatore);
    gestore.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_punteggio = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_punteggio.setText("PUNTEGGIO");

        lblTimer.setText("TEMPO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_punteggio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_punteggio)
                    .addComponent(lblTimer))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lbl_punteggio;
    // End of variables declaration//GEN-END:variables
}
