/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acchiappalatalpa;

/**
 *
 * @author onorati.nicolo
 */
import java.awt.Color;
import javax.swing.*;

import java.awt.Color;
import java.util.ArrayList;


public class Interfaccia extends javax.swing.JFrame {
    private ArrayList<RoundButton> listaBuche = new ArrayList<>();
    private Gestore gestore;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaccia.class.getName());

    /**
     * Creates new form Interfaccia
     */
    
   public Interfaccia() {
        // Setup base
        setTitle("Acchiappa la Talpa");
        setSize(450, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        getContentPane().setLayout(null);

        int buttonSize = 100;
        int gap = 20;
        int startX = 50;
        int startY = 50;

        // Ciclo per creare e AGGIUNGERE le buche
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                RoundButton hole = new RoundButton("");
                hole.setBackground(Color.lightGray);
                int x = startX + col * (buttonSize + gap);
                int y = startY + row * (buttonSize + gap);
                hole.setBounds(x, y, buttonSize, buttonSize);
                
                // IMPORTANTE: Aggiungi alla lista prima di passare al gestore
                listaBuche.add(hole); 
                getContentPane().add(hole);
            }
        }
        
       // 2. AVVIO DEL CICLO INFINITO
        // Creiamo il gestore passandogli le buche appena create
        gestore = new Gestore(listaBuche);
        
        // Facciamo partire il thread del gestore che gestirà il ciclo infinito
        gestore.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaccia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
